<div id="delivery-instructions">
    <strong><?php echo __('Instructions') ?>:</strong>
    <span class="price"><?=$block->getDeliveryInstructions() ?></span>
</div>
<script type="text/javascript">
    require(
        ['jquery'],
        function($) {
            var element = $('#delivery-instructions').detach();
            $('.order-shipping-method').append(element);
        }
    );
</script>